apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagram-cluster
  region: us-east-2
  version: '1.17'  
managedNodeGroups:
  - name: linux-ng
    instanceType: t3.small
    minSize: 2

nodeGroups:
  - name: udagram-node-eks
    instanceType: t3.small
    minSize: 2
    volumeSize: 100
    amiFamily: WindowsServer2019FullContainer